version: '3.7'
services:
  links:
    build: .
    env_file: docker/.env
    container_name: links
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:9.5-alpine
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5454:5432
    env_file: docker/.env
